---
- name: Deploy Nessus Agent
  hosts: agents
  gather_facts: yes
  become: yes
  vars:
    force_relink: true

  tasks:

    - name: Print host starting deployment
      debug:
        msg: "{{ inventory_hostname }}: Starting deployment"

    # ---------------- Rapid7 Removal ----------------
    - name: Upload Rapid7 remover
      copy:
        src: "r7remover.sh"
        dest: /tmp/r7remover.sh
        mode: "0755"
      when: remove_rapid7 | bool

    - name: Run Rapid7 remover script
      shell: "/bin/bash /tmp/r7remover.sh"
      register: r7_result
      ignore_errors: yes
      when: remove_rapid7 | bool

    - name: Print Rapid7 removal status
      debug:
        msg: "{{ inventory_hostname }}: Rapid7 removed"
      when:
        - remove_rapid7 | bool
        - r7_result is defined
        - r7_result.rc == 0

    # ---------------- Unsupported OS Check ----------------
    - name: Fail if OS unsupported
      fail:
        msg: "{{ inventory_hostname }}: Unsupported OS {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
      when: ansible_facts['distribution'] not in ['RedHat', 'Ubuntu', 'Debian']

    # ---------------- Remove existing Nessus token ----------------
    - name: Remove existing Nessus token if force_relink
      shell: "/opt/nessus_agent/sbin/nessuscli agent unlink"
      ignore_errors: yes
      when: force_relink

    # ---------------- RHEL 7 ----------------
    - name: Upload RHEL 7 package
      copy:
        src: "el7.rpm"
        dest: "/tmp/el7.rpm"
        mode: "0755"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Install RHEL 7 package
      command: yum -y localinstall /tmp/el7.rpm
      register: rpm_result
      ignore_errors: yes
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Print RHEL 7 install status
      debug:
        msg: "{{ inventory_hostname }}: Tenable installed"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"
        - rpm_result is defined
        - rpm_result.rc == 0

    # ---------------- RHEL 8 ----------------
    - name: Upload RHEL 8 package
      copy:
        src: "el8.rpm"
        dest: "/tmp/el8.rpm"
        mode: "0755"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Install RHEL 8 package
      command: dnf -y localinstall /tmp/el8.rpm
      register: rpm8_result
      ignore_errors: yes
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Print RHEL 8 install status
      debug:
        msg: "{{ inventory_hostname }}: Tenable installed"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"
        - rpm8_result is defined
        - rpm8_result.rc == 0

    # ---------------- RHEL 9 ----------------
    - name: Upload RHEL 9 package
      copy:
        src: "el9.rpm"
        dest: "/tmp/el9.rpm"
        mode: "0755"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"

    - name: Install RHEL 9 package
      command: dnf -y localinstall /tmp/el9.rpm
      register: rpm9_result
      ignore_errors: yes
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"

    - name: Print RHEL 9 install status
      debug:
        msg: "{{ inventory_hostname }}: Tenable installed"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"
        - rpm9_result is defined
        - rpm9_result.rc == 0

    # ---------------- Debian / Ubuntu ----------------
    - name: Upload Debian/Ubuntu package
      copy:
        src: "NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        dest: "/tmp/NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        mode: "0755"
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

    - name: Install Debian/Ubuntu package
      apt:
        deb: "/tmp/NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        state: present
      register: deb_result
      ignore_errors: yes
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

    - name: Print Debian/Ubuntu install status
      debug:
        msg: "{{ inventory_hostname }}: Tenable installed"
      when:
        - ansible_facts['distribution'] in ['Ubuntu', 'Debian']
        - deb_result is defined
        - deb_result.changed | default(false)

    # ---------------- Start & Link Nessus Agent ----------------
    - name: Enable and start Nessus Agent
      service:
        name: nessusagent
        state: started
        enabled: yes

    - name: Link Nessus Agent
      shell: >
        /opt/nessus_agent/sbin/nessuscli agent link
        --key={{ activation_key }}
        {% if mode == "cloud" %}
        --cloud
        {% else %}
        --manager-host={{ manager_host }} --manager-port={{ manager_port }}
        {% endif %}
      args:
        creates: "/opt/nessus_agent/.nessus/agent.key"
      register: link_result
      ignore_errors: yes

    - name: Print linking result
      debug:
        msg: >
          {{ inventory_hostname }}: 
          {% if link_result.rc == 0 %}Success{% else %}Failed{% endif %}
