---
- name: Deploy Nessus Agent
  hosts: agents
  gather_facts: no
  become: yes
  vars:
    force_relink: true
    ansible_remote_tmp: /tmp
    ansible_become_flags: "-S -tt"

  tasks:

    # ---------------- Remove Rapid7 ----------------
    - name: Upload Rapid7 remover as normal user
      copy:
        src: "r7remover.sh"
        dest: /tmp/r7remover.sh
        mode: "0755"
      become: no
      when: remove_rapid7 | bool

    - name: Run Rapid7 remover script
      command: /bin/bash /tmp/r7remover.sh
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"
      when: remove_rapid7 | bool

    # ---------------- Remove existing Nessus token ----------------
    - name: Remove existing Nessus token if force_relink
      shell: "/opt/nessus_agent/sbin/nessuscli agent unlink"
      ignore_errors: yes
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"
      when: force_relink

    # ---------------- RHEL 7 ----------------
    - name: Upload RHEL 7 package as normal user
      copy:
        src: "el7.rpm"
        dest: "/tmp/el7.rpm"
        mode: '0755'
      become: no
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Install RHEL 7 package
      command: yum -y localinstall /tmp/el7.rpm
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    # ---------------- RHEL 8 ----------------
    - name: Upload RHEL 8 package as normal user
      copy:
        src: "el8.rpm"
        dest: "/tmp/el8.rpm"
        mode: '0755'
      become: no
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Install RHEL 8 package
      command: dnf -y localinstall /tmp/el8.rpm
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    # ---------------- RHEL 9 ----------------
    - name: Upload RHEL 9 package as normal user
      copy:
        src: "el9.rpm"
        dest: "/tmp/el9.rpm"
        mode: '0755'
      become: no
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"

    - name: Install RHEL 9 package
      command: dnf -y localinstall /tmp/el9.rpm
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"

    # ---------------- Debian/Ubuntu ----------------
    - name: Upload Debian/Ubuntu package as normal user
      copy:
        src: "NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        dest: "/tmp/NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        mode: '0755'
      become: no
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

    - name: Install Debian/Ubuntu package
      apt:
        deb: "/tmp/NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        state: present
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

    # ---------------- Start & Link Nessus Agent ----------------
    - name: Enable and start Nessus Agent
      service:
        name: nessusagent
        state: started
        enabled: yes
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"

    - name: Link Nessus Agent
      shell: >
        /opt/nessus_agent/sbin/nessuscli agent link
        --key={{ activation_key }}
        {% if mode == "cloud" %}
        --cloud
        {% else %}
        --manager-host={{ manager_host }} --manager-port={{ manager_port }}
        {% endif %}
      args:
        creates: "/opt/nessus_agent/.nessus/agent.key"
      become: yes
      become_method: "{{ escalate_method }}"
      become_flags: "-S -tt"
